### PR TITLE
conversion of ontology information to nodes and links

### PR DESCRIPTION
**Pull request by SepidehAlassi**
PR corresponding to [DSP-136](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-26?issue=DSP-136)

This PR is only about the conversion of ontology information to graph data. The visualization is happening in a separate [app](https://github.com/SepidehAlassi/ontoVis) that needs Angular 9.

### CODE REVIEW

**Comment by kilchenmann** [comment]
It doesn't work on my computer. After running `yarn install` the yarn.lock file has been updated, which should not happen. This file should already be ready. The changes concern d3 packages.

**Comment by flavens** [comment]
I can serve it locally and no errors. But the yarn.lock file is also updated. It concerns 3d-force-graph.
Should I visualize something in the UI?

**Comment by kilchenmann** [comment]
I got an `Uncaught SyntaxError` from a "unknown" script.js. I don't know if it comes from d3 stuff or not.

Screen Shot 2020-04-17 at 09 53 06

@flavens Yes, you should see an ontology-graph-view at the bottom of data-model viewer

Screen Shot 2020-04-17 at 09 56 36

**Comment by kilchenmann** [comment]
Btw why is the "Review requested" already green? None of us has approved yet...

**Comment by SepidehAlassi** [comment]
> I got an `Uncaught SyntaxError` from a "unknown" script.js. I don't know if it comes from d3 stuff or not.

yes, it results from d3 library but it doesn't affect the conversion.

**Comment by SepidehAlassi** [comment]
> Btw why is the "Review requested" already green? None of us has approved yet...

The reason is that I am trying to merge this branch to wip/simple-ontology-creator and not to master/develop. Only direct merges to the master branch require PR approval.

**Comment by SepidehAlassi** [comment]
> I can serve it locally and no errors. But the yarn.lock file is also updated. It concerns 3d-force-graph.
> Should I visualize something in the UI?

no, this PR is just for the conversion of resource classes and properties to nodes and links of the graph for visualization. If you would like to visualize something, you should feed the generated `gData-json` in JSON format to the [OntoVis app](https://github.com/SepidehAlassi/ontoVis).

**Comment by SepidehAlassi** [comment]
> It doesn't work on my computer. After running `yarn install` the yarn.lock file has been updated, which should not happen. This file should already be ready. The changes concern d3 packages.

hmm I have not pushed the changes of yarn.lock to the branch, just updated the package.json so that locally yarn.lock would be updated. If necessary I can push the yarn.lock changes.

**Comment by kilchenmann** [comment]
> I have not pushed the changes of yarn.lock to the branch, just updated the package.json so that locally yarn.lock would be updated. If necessary I can push the yarn.lock changes.

yes please. yarn.lock (package-lock.json in case of npm) is always part of the app. s. https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by SepidehAlassi** [comment]
> > I have not pushed the changes of yarn.lock to the branch, just updated the package.json so that locally yarn.lock would be updated. If necessary I can push the yarn.lock changes.
> 
> yes please. yarn.lock (package-lock.json in case of npm) is always part of the app. s. https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

done!

**Comment by SepidehAlassi** [comment]
> > I got an `Uncaught SyntaxError` from a "unknown" script.js. I don't know if it comes from d3 stuff or not.
> 
> yes, it results from d3 library but it doesn't affect the conversion.

@kilchenmann I found what caused the syntax error: it was resulting from incorrect loading of d3-forc-3d library. I just fixed it. However in daily scrum meeting, you mentioned that you see errors (plural), is there any other error you encounter?

**Comment by kilchenmann** [comment]
I don't know exactly where the `Uncaught SyntaxError: Unexpected token 'export' ... scripts.js:114` comes from. It could be a ES6 issue because our setup is es2015. The solution could be to install `babel` as some stackoverflow comments propose, but it's not the solution right now. Probably it will disappear  after upgrading to angular-9?

**Comment by SepidehAlassi** [comment]
> I don't know exactly where the `Uncaught SyntaxError: Unexpected token 'export' ... scripts.js:114` comes from. It could be a ES6 issue because our setup is es2015. The solution could be to install `babel` as some stackoverflow comments propose, but it's not the solution right now. Probably it will disappear after upgrading to angular-9?

with the latest commit you should not get that error anymore. Please pull it again.

> I don't know exactly where the `Uncaught SyntaxError: Unexpected token 'export' ... scripts.js:114` comes from. It could be a ES6 issue because our setup is es2015. The solution could be to install `babel` as some stackoverflow comments propose, but it's not the solution right now. Probably it will disappear after upgrading to angular-9?

with the latest commit, you should not see the error anymore. Please pull again

**Comment by kilchenmann** [comment]
> Please pull it again.

This is what I did before running again. I also cleaned the cache etc. But will try again...

**Comment by kilchenmann** [comment]
now..it runs without error. Probably I didn't run `yarn install` after pulling. Weird sometimes

**Comment by kilchenmann** [comment]
> Btw why is the "Review requested" already green? None of us has approved yet...

ah...because we do not merge into master branch 🙈

**Comment by SepidehAlassi** [comment]
@kilchenmann @flavens Thank you for the review!

**Pull request merged**
